_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: outputs/finetune/moirai_1.0_R_small/load_data/6th_run/checkpoints/epoch=8-step=468.ckpt
num_samples: 100
patch_size: ???
context_length: ???
