hydra:
  run:
    dir: outputs/finetune/${hydra:runtime.choices.model}/${run_name}
defaults:
  - model: moirai_small
  - data: null
  - val_data: null
  - _self_
run_name: null
seed: 0
tf32: true
compile: false  # set to mode: default, reduce-overhead, max-autotune

#### Iterative training arguments ####
num_of_weeks: 26
iter_step: 1
######################################

dataset_path: data/it_load_data_23_24.csv
train_dataset_name: it_load_data_train
val_dataset_name: it_load_data_eval
model_dirpath: ${hydra:runtime.output_dir}/checkpoints/
trainer:
  _target_: lightning.Trainer
  accelerator: cpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32
  num_sanity_val_steps: 0
  logger:
      _target_: lightning.pytorch.loggers.TensorBoardLogger
      save_dir: ${hydra:runtime.output_dir}
      name: logs
  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: epoch
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: null
      monitor: val/PackedMSELoss
      save_weights_only: true
      mode: min
      save_top_k: 1
      every_n_epochs: 1
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val/PackedMSELoss
      min_delta: 1000
      patience: 15
      mode: min
      strict: false
      verbose: true
  max_epochs: 1
  enable_progress_bar: true
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
train_dataloader:
  _target_: uni2ts.data.loader.DataLoader
  batch_size: 8
  batch_size_factor: 1
  cycle: true
  num_batches_per_epoch: 1
  shuffle: false
  num_workers: 8
  collate_fn:
    _target_: uni2ts.data.loader.PackCollate
    max_length: ${model.module_kwargs.max_seq_len}
    seq_fields: ${cls_getattr:${model._target_},seq_fields}
    pad_func_map: ${cls_getattr:${model._target_},pad_func_map}
  pin_memory: true
  drop_last: false
  fill_last: false
  worker_init_fn: null
  prefetch_factor: 2
  persistent_workers: true
val_dataloader:
  _target_: uni2ts.data.loader.DataLoader
  batch_size: 256
  batch_size_factor: 10
  cycle: false
  num_batches_per_epoch: null
  shuffle: false
  num_workers: 8
  collate_fn:
    _target_: uni2ts.data.loader.PackCollate
    max_length: ${model.module_kwargs.max_seq_len}
    seq_fields: ${cls_getattr:${model._target_},seq_fields}
    pad_func_map: ${cls_getattr:${model._target_},pad_func_map}
  pin_memory: false
  drop_last: false
  fill_last: true
  worker_init_fn: null
  prefetch_factor: 2
  persistent_workers: true